### ISSUE TITLE
Quality of Life Features (QLF)

### ISSUE THREAD

**Issue by Broondoon** [Broondoon/build-stats#33]
Features which improve the core experience of the app. Most are short and sweet, barring that first one.

- [ ] QLF: User-based Access
- [x] #45
- [x] QLF: Responsive UI (Toggled / Reactive Buttons)
- [ ] QLF: One-Time Landing Page Decision
- [x] QLF: Responsive Buttons
- [ ] QLF: Flag Items
- [ ] QLF: Changed items light

**Comment by Broondoon** [comment]
A lot of these features, while nice, were triaged out of the scope.
